nmanage/urls.py
from django.contrib import admin
from django.urls import path, include

import nmanage.resources.views as resource_views


urlpatterns = [
  path('social-auth/', include('social_django.urls', namespace='social')),
  path('admin/', admin.site.urls),
  path('accounts/login/', resource_views.login_view),
  path('resources/list/', resource_views.my_resources),
  path('resources/action/<slug:action>/<int:rid>/', resource_views.execute_action),
  path('resources/wait/<slug:action>/<int:rid>/', resource_views.wait_action),
  path('resources/info/<int:rid>/', resource_views.view_info),
  path('resources/info/<int:rid>/edit-schedule/', resource_views.edit_schedule),
  path('', resource_views.home),
]

nmanage/resources/models.py
import datetime

from django.core import validators
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone

import boto3
from botocore.exceptions import ClientError

from encrypted_model_fields.fields import EncryptedCharField


class AwsAccount(models.Model):
  name = models.CharField(max_length=75)

  key_id = models.CharField(max_length=128)
  key_secret = EncryptedCharField(max_length=255)

  created = models.DateTimeField(auto_now_add=True, db_index=True)
  modified = models.DateTimeField(auto_now=True, db_index=True)

  def __str__(self):
    return self.name

  @property
  def client_kwargs(self):
    return {
      'aws_access_key_id': self.key_id,
      'aws_secret_access_key': self.key_secret,
    }


class HostedZone(models.Model):
  name = models.CharField(max_length=75)
  base_domain = models.CharField(max_length=255)
  zone_id = models.CharField(max_length=255, blank=True, null=True)

  account = models.ForeignKey(AwsAccount, on_delete=models.CASCADE, blank=True, null=True)

  created = models.DateTimeField(auto_now_add=True, db_index=True)
  modified = models.DateTimeField(auto_now=True, db_index=True)

  def __str__(self):
    return self.name

  def update_record(self, name, ip):
    if self.zone_id and self.account:
      client = boto3.client('route53', **self.account.client_kwargs)
      response = client.change_resource_record_sets(
        ChangeBatch={
          'Changes': [
              {
                'Action': 'UPSERT',
                'ResourceRecordSet': {
                  'Name': f'{name}.{self.base_domain}',
                  'ResourceRecords': [{'Value': ip}],
                  'TTL': 300,
                  'Type': 'A',
                },
              },
          ]
        },
        HostedZoneId=self.zone_id
      )


class Region(models.Model):
  name = models.CharField(max_length=75)
  region = models.CharField(max_length=25, blank=True, null=True, validators=[validators.validate_slug])
  endpoint = models.CharField(max_length=128, blank=True, null=True)
  account = models.ForeignKey(AwsAccount, on_delete=models.CASCADE)

  created = models.DateTimeField(auto_now_add=True, db_index=True)
  modified = models.DateTimeField(auto_now=True, db_index=True)

  def __str__(self):
    return self.name

  @property
  def client_kwargs(self):
    ret = self.account.client_kwargs

    if self.endpoint:
      ret['endpoint_url'] = self.endpoint

    if self.region:
      ret['region_name'] = self.region

    return ret

  def client(self, rtype):
    return boto3.client(rtype, **self.client_kwargs)

  def get_ec2_infos(self, rids):
    ret = {}

    for rid in rids:
      try:
        response = self.client('ec2').describe_instances(InstanceIds=[rid])

      except ClientError:
        continue

      for rserv in response['Reservations']:
        for instance in rserv['Instances']:
          ret[instance['InstanceId']] = instance

    return ret

class Resource(models.Model):
  class ResourceTypes(models.TextChoices):
    EC2 = 'EC2', 'EC2'

  class ZoneUpdateTypes(models.TextChoices):
    PUBLIC = 'PUBLIC', 'Public'
    PRIVATE = 'PRIVATE', 'Private'

  name = models.CharField(max_length=75, validators=[validators.validate_slug])
  rid = models.CharField('Resource ID', max_length=75)
  rtype = models.CharField('Resource Type', max_length=10, choices=ResourceTypes.choices)

  region = models.ForeignKey(Region, on_delete=models.SET_NULL, blank=True, null=True)
  zone = models.ForeignKey(HostedZone, on_delete=models.SET_NULL, blank=True, null=True)
  zone_update = models.CharField(max_length=10, choices=ZoneUpdateTypes.choices)
  last_zone_ip = models.CharField(max_length=75, blank=True, null=True)

  disable_power_schedule = models.BooleanField(default=False)

  created = models.DateTimeField(auto_now_add=True, db_index=True)
  modified = models.DateTimeField(auto_now=True, db_index=True)

  def __str__(self):
    return self.name

  @property
  def dns(self):
    if self.zone:
      return f'{self.name}.{self.zone.base_domain}'

  @property
  def account(self):
    if self.region:
      return self.region.account

  @property
  def endpoint(self):
    if self.region:
      return self.region.endpoint

  @property
  def region_code(self):
    if self.region:
      return self.region.region

  @property
  def client(self):
    return self.region.client(self.rtype.lower())

  def uptime(self, launch_time=None):
    if self.rtype == 'EC2':
      if launch_time is None:
        if hasattr(self, 'api_data'):
          if self.api_data['State']['Name'] == 'running' and self.api_data['LaunchTime']:
            launch_time = self.api_data['LaunchTime']

      if launch_time is not None:
        tdelta = timezone.now() - launch_time
        return tdelta

  def execute(self, action):
    method = f"{self.rtype.lower()}_{action}"
    return getattr(self, method)()

  def get_info(self):
    response = self.client.describe_instances(InstanceIds=[self.rid])
    return response['Reservations'][0]['Instances'][0]

  def is_done(self, action):
    response = self.client.describe_instances(InstanceIds=[self.rid])
    state = response['Reservations'][0]['Instances'][0]['State']['Name']

    if action in ['stop', 'force_stop']:
      return state == 'stopped'

    if action in ['start', 'reboot']:
      if state == 'running':
        if self.zone:
          self.update_zone_record(response['Reservations'][0]['Instances'][0])

      return state == 'running'

    return False

  def update_zone_record(self, info):
    if self.zone_update == 'PUBLIC':
      ip = info['PublicIpAddress']

    else:
      ip = info['PrivateIpAddress']

    if self.last_zone_ip != ip:
      self.zone.update_record(self.name, ip)
      self.last_zone_ip = ip
      self.save()

  def ec2_start(self):
    self.client.start_instances(InstanceIds=[self.rid])
    return True

  def ec2_stop(self):
    self.client.stop_instances(InstanceIds=[self.rid])
    return True

  def ec2_force_stop(self):
    self.client.stop_instances(InstanceIds=[self.rid], Force=True)
    return True

  def ec2_reboot(self):
    self.client.reboot_instances(InstanceIds=[self.rid])


class Permission(models.Model):
  class AvailableActions(models.TextChoices):
    POWER = 'power', 'Power On/Off'
    SCHEDULE = 'schedule', 'Edit Schedule'

  ACTION_MAP = {
    AvailableActions.POWER.value: ['start', 'stop', 'reboot', 'force_stop']
  }

  resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

  actions = ArrayField(
    models.CharField('Action Type', max_length=10, choices=AvailableActions.choices)
  )

  do_not_save = False

  def save(self):
    if self.do_not_save:
      return

    return super().save()


def SuperPermission(user, action, rid):
  perm = Permission(user=user, resource_id=rid, actions=[action])
  perm.do_not_save = True
  return perm


class PowerSchedule(models.Model):
  class EventTypes(models.TextChoices):
    ON = 'ON'
    OFF = 'OFF'

  resource = models.ForeignKey(Resource, on_delete=models.CASCADE)

  event_ts = models.DateTimeField(db_index=True)
  event_type = models.CharField(max_length=3, choices=EventTypes.choices)

  last_executed = models.DateTimeField(blank=True, null=True)

  created = models.DateTimeField(auto_now_add=True, db_index=True)
  modified = models.DateTimeField(auto_now=True, db_index=True)

  class Meta:
    ordering =('event_ts',)

  def __str__(self):
    return '{} {}'.format(self.resource.name, self.event_type)

  def reschedule(self):
    new_event = self.event_ts + datetime.timedelta(days=7)
    new_event = new_event.replace(hour=self.event_ts.hour)
    self.event_ts = new_event


def rebuild_schedule(tz, resource, schedule_data):
  PowerSchedule.objects.filter(resource=resource).delete()

  days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
  for i, day in enumerate(days, start=1):
    for t in ['on', 'off']:
      key = f'{day}_{t}'
      if schedule_data[key]:
        value = schedule_data[key]
        now = timezone.now()
        ts = timezone.now()
        if tz:
          ts = ts.astimezone(tz)

        ts = ts.replace(hour=value.hour, minute=value.minute, second=0)
        if ts > now:
          pass

        else:
          ts = ts + datetime.timedelta(days=1)

        while 1:
          if ts.isoweekday() == i:
            break

          else:
            ts = ts + datetime.timedelta(days=1)

        ps = PowerSchedule(resource=resource, event_type=t.upper(), event_ts=ts)
        ps.save()

nmanage/resources/templates/resources/edit_schedule.html
{% extends "nmanage_base.html" %}{% load humanize rtags %}
{% block title %}Edit Schedule: {{ resource.name }} | {{ block.super }}{% endblock %}
{% block content %}
<v-card style="margin: 10px auto; max-width: 500px;">
  <v-card-title class="text-center">
    Edit Schedule: {{ resource.name }}
  </v-card-title>
  <v-card-text>
    <v-container style="max-width: 100%;">
      <form action="./" method="POST">
        {% csrf_token %}
        <ul class="main-form">{{ form_render|safe }}</ul>
        <v-btn color="primary" type="submit">
          Save
        </v-btn>
      </form>
    </v-container>
  </v-card-text>
</v-card>
{% endblock %}
{% block mixin %}
<style>
  ul.main-form {
    margin: 0;
    padding: 0;
    list-style-type: none;
  }

  ul.main-form li {
    margin: 0;
    padding: 0;
  }
</style>
<script>
  var MIXIN = {
    data() {
      return {
        disabled: {% if form.data.disabled %}'ON'{% else %}false{% endif %}
      }
    },
    mounted() {

    },
    methods: {

    }
  };
</script>
{% endblock %}

nmanage/resources/templates/resources/info.html
{% extends "nmanage_base.html" %}{% load humanize rtags %}
{% block title %}{{ resource.rtype }}: {{ resource.name }} | {{ block.super }}{% endblock %}
{% block content %}
<v-card style="margin: 10px auto; max-width: 500px;">
  <v-card-title class="text-center">
    {{ resource.rtype }}: {{ resource.name }}
  </v-card-title>
  <v-card-text>
    <v-container style="max-width: 100%;">
      <div>
        <v-select
          outlined
          dense
          :items="{{ resource|actions:request.user|safe }}"
          label="Actions"
          @change="run_action('{{ resource.id }}', '{{ resource.name|escapejs }}')"
          v-model="resource"
        ></v-select>
      </div>
      <v-simple-table>
        <template v-slot:default>
          <thead>
            <tr>
              <th class="text-left">
                Attribute
              </th>
              <th class="text-left">
                Value
              </th>
            </tr>
          </thead>
          <tbody>
            {% if resource.zone %}
            <tr>
              <td><strong>DNS</strong></td>
              <td>{{ resource.dns }}</td>
            </tr>
            {% endif %}
            {% for key, value in info.items %}
            <tr>
              <td><strong>{{ key }}</strong></td>
              <td>{{ value }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </template>
      </v-simple-table>
      <v-divider></v-divider>
      <br>
      {% if request.user|can_schedule:resource %}
      <v-btn class="float-right" color="primary" small href="./edit-schedule/">Edit Schedule</v-btn>
      {% endif %}
      <h3>Power Scheduling</h3>
      <br>
      <strong>Power Scheduling Disabled: {{ resource.disable_power_schedule }}</strong>
      <v-simple-table>
        <template v-slot:default>
          <thead>
            <tr>
              <th class="text-left">
                Event Time
              </th>
              <th class="text-left">
                Event Type
              </th>
            </tr>
          </thead>
          <tbody>
            {% for event in resource.powerschedule_set.all %}
            <tr>
              <td><strong>{{ event.event_ts|date:"l, h:i A" }}</strong></td>
              <td>{{ event.event_type }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </template>
      </v-simple-table>
    </v-container>
  </v-card-text>
</v-card>
{% endblock %}
{% block mixin %}
<script>
  var MIXIN = {
    data() {
      return {resource: null}
    },
    mounted() {

    },
    methods: {
      run_action(rid, name) {
        var ans = confirm(`Are you sure you wish to ${this.resource} ${name}?`);
        if (ans) {
          location.href = `../../action/${this.resource}/${rid}/?ts=${Date.now()}`;
        } else{
          this.$nextTick(() => {
            this.resource = null;
          });
        }
      }
    }
  };
</script>
{% endblock %}

nmanage/resources/templates/resources/list.html
{% extends "nmanage_base.html" %}{% load humanize rtags %}
{% block title %}My Resources | {{ block.super }}{% endblock %}
{% block content %}
<v-card style="margin: 10px;">
  <v-card-title>
    My Resources
  </v-card-title>
  <v-card-text>
    <v-container style="max-width: 100%;">
      <div class="d-flex">
        <div>
          <form action="./" method="GET" class="d-flex align-center">
            <v-text-field name="search" outlined label="Search" dense value="{{ search }}"></v-text-field>
            <v-btn type="submit" icon small>
              <v-icon class="mdi mdi-send"></v-icon>
            </v-btn>
          </form>
        </div>
        <div class="flex-grow-1 d-flex justify-end">
          <v-pagination v-model="page" :length="{{ page_obj.paginator.num_pages }}"></v-pagination>
        </div>
      </div>
      <v-simple-table>
        <template v-slot:default>
          <thead>
            <tr>
              <th class="text-left">
                Resource
              </th>
              <th class="text-left">
                Resource
              </th>
              <th class="text-left">
                Region
              </th>
              <th class="text-left">
                Type
              </th>
              <th class="text-left">
                IP
              </th>
              <th class="text-left">
                Uptime
              </th>
              <th class="text-left">
                State
              </th>
              <th class="text-left">
                Actions
              </th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for r in page_obj %}
            <tr>
              <td>
                <a href="../info/{{ r.id }}/">{% if r.dns %}{{ r.dns }}{% else %}{{ r.name }}{% endif %}</a>
              </td>
              <td>{{ r.rtype }}</td>
              <td>{{ r.region }}</td>
              <td>{{ r.api_data.InstanceType|default:"---" }}</td>
              <td>
                {% if r.zone_update == 'PUBLIC' %}
                {{ r.api_data.PublicIpAddress|default:"---" }}
                {% else %}
                {{ r.api_data.PrivateIpAddress|default:"---" }}
                {% endif %}
              </td>
              <td>{{ r.uptime|tdelta|default:"---" }}</td>
              <td>{{ r.api_data.State.Name|default:"---" }}</td>
              <td class="select">
                <v-select
                  outlined
                  dense
                  :items="{{ r|actions:request.user|safe }}"
                  label="Actions"
                  @change="run_action({{ forloop.counter0 }}, '{{ r.id }}', '{{ r.name|escapejs }}')"
                  v-model="resources[{{ forloop.counter0 }}]"
                ></v-select>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </template>
      </v-simple-table>
      <div class="d-flex justify-end">
        <v-pagination v-model="page" :length="{{ page_obj.paginator.num_pages }}"></v-pagination>
      </div>
    </v-container>
  </v-card-text>
</v-card>
{% endblock %}
{% block mixin %}
<style>
  .v-text-field__details {
    display: none;
  }

  td.select > div {
    transform: scale(0.7);
  }
</style>
<script>
  var MIXIN = {
    data() {
      return {
        page : {{ page_obj.number }},
        resources: new Array({{ page_obj.object_list|length }})
      }
    },
    watch: {
      page(to, from) {
        var url = new URL(location.href);
        url.searchParams.set('page', to);
        location.href = url.href;
      }
    },
    methods: {
      run_action(i, rid, name) {
        var ans = confirm(`Are you sure you wish to ${this.resources[i]} ${name}?`);
        if (ans) {
          location.href = `../action/${this.resources[i]}/${rid}/?ts=${Date.now()}`;
        } else{
          this.$nextTick(() => {
            this.$set(this.resources, i, undefined);
          });
        }
      }
    }
  };
</script>
{% endblock %}

nmanage/resources/templates/resources/login.html
{% extends "nmanage_base.html" %}{% load humanize rtags %}
{% block title %}Login | {{ block.super }}{% endblock %}
{% block content %}
<v-card style="margin: 10px auto; max-width: 500px;">
  <v-card-title class="text-center">
    Login to Continue
  </v-card-title>
  <v-card-text>
    <v-container style="max-width: 100%;">
      {% for b in bclasses %}
      <v-btn href="{% url 'social:begin' b.name %}?next={{ next }}" color="primary">{{ b.display_name }}</v-btn>
      {% endfor %}
    </v-container>
  </v-card-text>
</v-card>
{% endblock %}
{% block mixin %}
<script>
  var MIXIN = {
    data() {
      return {}
    },
    mounted() {

    }
  };
</script>
{% endblock %}

nmanage/resources/templates/resources/wait.html
{% extends "nmanage_base.html" %}{% load humanize rtags %}
{% block title %}Wait for Action | {{ block.super }}{% endblock %}
{% block content %}
<v-card style="margin: 10px auto; max-width: 500px;">
  <v-card-title class="text-center">
    Waiting for Action to Complete
  </v-card-title>
  <v-card-text>
    <v-container style="max-width: 100%;">
      <div class="text-center">
        <v-progress-circular :size="96" color="primary" indeterminate></v-progress-circular>
      </div>
    </v-container>
  </v-card-text>
</v-card>
{% endblock %}
{% block mixin %}
<script>
  var MIXIN = {
    data() {
      return {}
    },
    mounted() {
      setTimeout(() => {
        location.href = `${location.pathname}?ts=${Date.now()}`;
      }, 10 * 1000);
    }
  };
</script>
{% endblock %}